// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRttsiutDg9wprmI8S5tNdtkid5RvK2o4',
    appId: '1:847467938211:web:65cb8aa0deb448b9785a16',
    messagingSenderId: '847467938211',
    projectId: 'ngo-app-d7f4e',
    authDomain: 'ngo-app-d7f4e.firebaseapp.com',
    storageBucket: 'ngo-app-d7f4e.appspot.com',
    measurementId: 'G-6WSCEYBHPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLukReh9TdqoWKgFtuT6FcAsx3yd0BXBo',
    appId: '1:847467938211:android:6869bd30320dff06785a16',
    messagingSenderId: '847467938211',
    projectId: 'ngo-app-d7f4e',
    storageBucket: 'ngo-app-d7f4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVS9WW9ahHX3Yuf0QQDeqoepB-l_2T_xk',
    appId: '1:847467938211:ios:659479c64fd9dfec785a16',
    messagingSenderId: '847467938211',
    projectId: 'ngo-app-d7f4e',
    storageBucket: 'ngo-app-d7f4e.appspot.com',
    iosClientId: '847467938211-skoj3ldrs58gel2gh2uft7seg1d17kv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVS9WW9ahHX3Yuf0QQDeqoepB-l_2T_xk',
    appId: '1:847467938211:ios:eb938449ebe2d0b9785a16',
    messagingSenderId: '847467938211',
    projectId: 'ngo-app-d7f4e',
    storageBucket: 'ngo-app-d7f4e.appspot.com',
    iosClientId: '847467938211-170fv01cap4k6lmr4lavvlho43tvblfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ngoApp.RunnerTests',
  );
}
